.TH eza(1)

.SH NAME
.B eza 
- manage aliases from the command line

.SH SYNOPSIS
.B eza
.RB [ OPTION ]
.RB [ ALIAS ]
.RB [ COMMAND ]

.SH DESCRIPTION
.B eza 

Add/remove/list/edit aliases from the command line. Default rc file is $HOME/.zshrc.

.SS
.B
-a
.LP

This requires both the [ ALIAS ] and [ COMMAND ] arguments. It will add the alias with the passed command to the end of the rc file.

.SS
.B
-am
.LP

This creates the alias in the same way that -a does. The only difference is that once the alias has been created you will be prompted to fill in a brief man page that will be attached to the new alias. (Ex. if you create an alias named 'test' with -am you will create a man page which can be accessed with 'man test'.)

.SS
.B
-r
.LP

This only accepts an [ ALIAS ]. The passed [ ALIAS ] is removed, if found.


.SS
.B
-l
.LP

This will list all aliases in the rc file. 

.SS
.B
-cc
.LP

This requires both [ ALIAS ] and [ COMMAND ] arguments. It will replcae the existing command with the passed command. If no existing alias is found with the [ ALIAS ] name then a new alias will be created (just like -a).

.SH EXAMPLES

eza -a testalias "echo 'this is a test' "

eza -cc testalias "echo 'now it says this' "

eza -r testalias

eza -l




.SH NOTES
You may have to open a new shell for the new alias to be accessible.
